#!/usr/bin/env python3
"""core/tests/conformance/drm-abi/gen-table.py

Emits `table.h` -- the list of every `DRM_IOCTL_*` request this harness carries
across the boundary -- BY NAME ONLY. It never computes a request number.

THAT IS THE POINT AND IT IS WORTH BEING EXPLICIT ABOUT. A generator that parsed
`_IOWR(...)` and did the arithmetic itself would be a second implementation of
the `_IOC` encoding, and a harness whose expectation is its own second
implementation proves nothing about the first. So this file emits

    (unsigned int)DRM_IOCTL_VERSION,

and lets the C compiler -- the one targeting x86_64-unknown-none-elf, the one
whose `sizeof` is the ABI -- produce the number. The expectation the harness
compares against is produced by a DIFFERENT toolchain from DIFFERENT copies of
the headers (oracle.py), which is what makes the comparison mean something.

Usage:
    gen-table.py <libdrm-include-drm-dir> <out.h>

Exit status: 0 on success, 3 on a self-check failure.
"""

import re
import sys

# The headers whose ioctls this harness carries. drm.h is core DRM and KMS;
# virtgpu_drm.h is the per-driver set ADR-0029 names as the first driver.
HEADERS = ("drm.h", "virtgpu_drm.h")

# Names that are not requests. DRM_IOCTL_BASE is the type letter.
NOT_A_REQUEST = {"DRM_IOCTL_BASE"}


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: gen-table.py <libdrm-include-drm-dir> <out.h>")
    incdir, out = sys.argv[1], sys.argv[2]

    names = []
    for h in HEADERS:
        try:
            src = open("%s/%s" % (incdir, h)).read()
        except OSError as e:
            raise SystemExit("gen-table: cannot read %s/%s: %s" % (incdir, h, e))
        for m in re.finditer(r"^#define\s+(DRM_IOCTL_[A-Z0-9_]+)\s", src, re.M):
            n = m.group(1)
            if n in NOT_A_REQUEST or n in names:
                continue
            names.append(n)

    # Self-checks. A generator that silently produced an empty or truncated
    # table would make every assertion downstream vacuous.
    if len(names) < 100:
        raise SystemExit("gen-table: found only %d DRM_IOCTL_* names in %s; "
                         "expected the full uAPI (>=100)" % (len(names), incdir))
    for required in ("DRM_IOCTL_VERSION", "DRM_IOCTL_GET_CAP", "DRM_IOCTL_GEM_CLOSE",
                     "DRM_IOCTL_MODE_CREATE_DUMB", "DRM_IOCTL_MODE_ADDFB2",
                     "DRM_IOCTL_VIRTGPU_EXECBUFFER", "DRM_IOCTL_VIRTGPU_MAP"):
        if required not in names:
            raise SystemExit("gen-table: %s is not in the table; the headers at %s "
                             "are not the ones this harness was written against"
                             % (required, incdir))

    with open(out, "w") as f:
        f.write("/* GENERATED by gen-table.py from %s -- do not edit. */\n" % incdir)
        f.write("#define DRMABI_COUNT %d\n\n" % len(names))
        f.write("static const unsigned int drmabiVals[DRMABI_COUNT] = {\n")
        for n in names:
            f.write("  (unsigned int)%s,\n" % n)
        f.write("};\n\n")
        f.write("static const char *const drmabiNames[DRMABI_COUNT] = {\n")
        for n in names:
            # The DRM_IOCTL_ prefix is dropped: every name carries it, it costs
            # 10 bytes of .rodata each, and the program prints one line per
            # entry through a printf capped at 120 bytes.
            f.write('  "%s",\n' % n[len("DRM_IOCTL_"):])
        f.write("};\n")

    print("gen-table: %d requests -> %s" % (len(names), out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
