/* core/tests/conformance/drm-abi/prog.c
 *
 * A PROGRAM COMPILED AGAINST LINUX'S UNMODIFIED DRM uAPI HEADERS, RUNNING ON
 * OSCORTEX.
 *
 * It computes nothing about graphics and it issues no ioctl -- there is no
 * `ioctl` syscall on this operating system yet (GAP-0158, ADR-0031 §4). What it
 * does is the one thing that has to be true before anything above it can be:
 *
 *   * `include/drm/drm.h` and `include/drm/virtgpu_drm.h`, straight out of the
 *     pinned libdrm checkout with NO PATCH APPLIED, are #included by a program
 *     built for x86_64-unknown-none-elf against core/user/libc;
 *   * every `DRM_IOCTL_*` request number in them is computed BY THE COMPILER,
 *     from `sizeof` of the structs as this target lays them out;
 *   * the program runs in ring 3 on this kernel and reports those numbers;
 *   * and `_IOC_DIR`/`_IOC_SIZE`/`_IOC_TYPE`/`_IOC_NR` decode them back.
 *
 * WHY THE HASH. There are DRMABI_COUNT (121, at the pinned commit) requests and
 * one printf per request would be 121 golden lines for a claim that is really
 * one claim. So the program folds all of them into an FNV-1a/32 over their
 * little-endian bytes and prints that, plus nine named requests chosen because
 * they are the ones the first four rungs of drm-abi.md's ladder actually issue.
 * run.sh recomputes the same hash on the host from a DIFFERENT toolchain and a
 * DIFFERENT copy of the headers. A single wrong struct size anywhere in the
 * uAPI moves the hash.
 *
 * THE NEGATIVE CONTROL IS BUILT FROM THIS SAME FILE, unchanged: build-progs.sh
 * puts a `sys/ioccom.h` carrying BSD's `_IOC` encoding ahead of ours on the
 * include path. `drm.h` takes its "one of the BSDs" branch on this target --
 * `__linux__` is not defined for x86_64-unknown-none-elf and this port does not
 * pretend otherwise -- so the encoding that header finds is entirely ours to
 * choose, and choosing wrong is silent. It changes 29 of the 121 request
 * numbers, DRM_IOCTL_GEM_CLOSE and DRM_IOCTL_SET_CLIENT_CAP and
 * DRM_IOCTL_SET_MASTER among them, and leaves the other 92 alone. The control
 * must produce a DIFFERENT hash and the SAME count.
 *
 * printf here has five conversions and a 120-byte cap (ADR-0017 §5), which is
 * why every line below is short and why nothing prints a 64-bit value: a DRM
 * request number is 32 bits and `%x` takes an `unsigned int`, exactly.
 */

#include "oslibc.h"

#include <stdint.h>

/* THE UNMODIFIED uAPI. Everything these two headers need arrives through
 * core/user/ports/libdrm/shim -- <sys/ioccom.h>, <sys/types.h>, <stdint.h> --
 * and `sys/ioccom.h` is where this port makes its one substantive choice: it
 * serves LINUX's _IOC encoding, not BSD's. ADR-0031 §3. */
#include "drm.h"
#include "virtgpu_drm.h"

/* GENERATED by gen-table.py: DRMABI_COUNT, drmabiVals[], drmabiNames[]. Every
 * entry of drmabiVals is `(unsigned int)DRM_IOCTL_<NAME>` and is therefore the
 * compiler's arithmetic, not the generator's. */
#include "table.h"

/* .data, not .bss: m19-argv's build check requires the R+W segment to have real
 * file bytes so the loader's copy path runs for it, and this program has no
 * other mutable global. */
volatile unsigned int drmabiMarker = 0x0D8A0001u;

/* FNV-1a, 32-bit, over the little-endian bytes of every request number in
 * table order. Transcribed here and again in run.sh's python; the two are
 * independent implementations of a five-line function, which is the level of
 * duplication a checksum can carry without becoming its own oracle. */
static unsigned int fnv1a(const unsigned int *v, unsigned long n) {
  unsigned int h = 2166136261u;
  unsigned long i;
  for (i = 0; i < n; i++) {
    unsigned int x = v[i];
    unsigned int b;
    for (b = 0; b < 4; b++) {
      h ^= (x >> (b * 8)) & 0xFFu;
      h *= 16777619u;
    }
  }
  return h;
}

/* The nine requests drm-abi.md's R0-R3 rungs issue, named so that a moved hash
 * can be localised without a second boot. */
struct named {
  const char *name;
  unsigned int req;
};

int main(int argc, char **argv) {
  (void)argc;
  (void)argv;

  const struct named nine[9] = {
      {"VERSION", (unsigned int)DRM_IOCTL_VERSION},
      {"GET_CAP", (unsigned int)DRM_IOCTL_GET_CAP},
      {"SET_CLIENT_CAP", (unsigned int)DRM_IOCTL_SET_CLIENT_CAP},
      {"GEM_CLOSE", (unsigned int)DRM_IOCTL_GEM_CLOSE},
      {"PRIME_HANDLE_TO_FD", (unsigned int)DRM_IOCTL_PRIME_HANDLE_TO_FD},
      {"MODE_CREATE_DUMB", (unsigned int)DRM_IOCTL_MODE_CREATE_DUMB},
      {"MODE_MAP_DUMB", (unsigned int)DRM_IOCTL_MODE_MAP_DUMB},
      {"MODE_ADDFB2", (unsigned int)DRM_IOCTL_MODE_ADDFB2},
      {"VIRTGPU_EXECBUFFER", (unsigned int)DRM_IOCTL_VIRTGPU_EXECBUFFER},
  };

  printf("DRMABI START marker=%x", drmabiMarker);
  printf("DRMABI COUNT %d", (int)DRMABI_COUNT);
  printf("DRMABI HASH %x", fnv1a(drmabiVals, (unsigned long)DRMABI_COUNT));

  int i;
  for (i = 0; i < 9; i++) {
    printf("DRMABI REQ %s %x", nine[i].name, nine[i].req);
  }

  /* THE DECODE. A kernel serving this ABI must pull four fields out of the
   * request word; this proves the encoding those four fields were packed into
   * is the one this program's headers produced. `_IOC_TYPE` is printed as a
   * character as well as a number because 0x64 being 'd' is the whole of what
   * "the DRM ioctl group" means. */
  for (i = 0; i < 9; i++) {
    unsigned int r = nine[i].req;
    printf("DRMABI DEC %s dir=%d size=%d type=%c nr=%d", nine[i].name,
           (int)_IOC_DIR(r), (int)_IOC_SIZE(r), (char)_IOC_TYPE(r),
           (int)_IOC_NR(r));
  }

  /* THE STRUCT SIZES, separately from the request numbers that encode them.
   * `_IOC_SIZE` is 14 bits wide, so a struct of 16384 bytes or more would wrap
   * silently; printing sizeof alongside the encoded size is what makes the two
   * checkable against each other rather than against themselves. */
  printf("DRMABI SZ version=%d get_cap=%d set_client_cap=%d",
         (int)sizeof(struct drm_version), (int)sizeof(struct drm_get_cap),
         (int)sizeof(struct drm_set_client_cap));
  printf("DRMABI SZ gem_close=%d prime_handle=%d unique=%d",
         (int)sizeof(struct drm_gem_close), (int)sizeof(struct drm_prime_handle),
         (int)sizeof(struct drm_unique));
  printf("DRMABI SZ create_dumb=%d map_dumb=%d destroy_dumb=%d",
         (int)sizeof(struct drm_mode_create_dumb),
         (int)sizeof(struct drm_mode_map_dumb),
         (int)sizeof(struct drm_mode_destroy_dumb));
  printf("DRMABI SZ fb_cmd2=%d crtc=%d atomic=%d",
         (int)sizeof(struct drm_mode_fb_cmd2), (int)sizeof(struct drm_mode_crtc),
         (int)sizeof(struct drm_mode_atomic));
  printf("DRMABI SZ vg_execbuf=%d vg_map=%d vg_res_create=%d",
         (int)sizeof(struct drm_virtgpu_execbuffer),
         (int)sizeof(struct drm_virtgpu_map),
         (int)sizeof(struct drm_virtgpu_resource_create));
  printf("DRMABI SZ event=%d event_vblank=%d syncobj_handle=%d",
         (int)sizeof(struct drm_event), (int)sizeof(struct drm_event_vblank),
         (int)sizeof(struct drm_syncobj_handle));

  /* THE ENCODED SIZE IS THE STRUCT SIZE, asserted by the program against
   * `sizeof` for every one of the nine rather than left to a reader to compare
   * two printed columns. This is the property drm-abi.md §2.1 says a kernel
   * must not get wrong: the size is IN the request number, so a struct whose
   * layout differs from Linux's changes the number silently. */
  int szmatch = 0;
  const unsigned int nineSz[9] = {
      (unsigned int)sizeof(struct drm_version),
      (unsigned int)sizeof(struct drm_get_cap),
      (unsigned int)sizeof(struct drm_set_client_cap),
      (unsigned int)sizeof(struct drm_gem_close),
      (unsigned int)sizeof(struct drm_prime_handle),
      (unsigned int)sizeof(struct drm_mode_create_dumb),
      (unsigned int)sizeof(struct drm_mode_map_dumb),
      (unsigned int)sizeof(struct drm_mode_fb_cmd2),
      (unsigned int)sizeof(struct drm_virtgpu_execbuffer),
  };
  for (i = 0; i < 9; i++) {
    if (_IOC_SIZE(nine[i].req) == nineSz[i]) {
      szmatch++;
    }
  }
  printf("DRMABI SIZEENC %d of 9", szmatch);

  /* Two whole-table numbers the host can predict exactly: how many requests
   * carry no payload at all (`_IO`, which is what SET_MASTER and DROP_MASTER
   * are, and which the BSD encoding gets wrong in a way that is invisible in
   * every other field), and the largest payload any of them carries -- against
   * the 14-bit ceiling `_IOC_SIZE` imposes. */
  int zerosz = 0;
  unsigned int maxsz = 0;
  unsigned int i2;
  for (i2 = 0; i2 < (unsigned int)DRMABI_COUNT; i2++) {
    unsigned int s = _IOC_SIZE(drmabiVals[i2]);
    if (s == 0u) {
      zerosz++;
    }
    if (s > maxsz) {
      maxsz = s;
    }
  }
  printf("DRMABI ZEROSIZE %d MAXSIZE %d CEIL %d", zerosz, (int)maxsz, 16383);

  printf("DRMABI DONE");
  return 0;
}
