/* core/tests/conformance/drm-abi/prog.c
 *
 * A PROGRAM COMPILED AGAINST LINUX'S UNMODIFIED DRM uAPI HEADERS, RUNNING ON
 * OSCORTEX.
 *
 * It computes nothing about graphics and it issues no ioctl -- there is no
 * `ioctl` syscall on this operating system yet (GAP-0158, ADR-0031 §4). What it
 * does is the one thing that has to be true before anything above it can be:
 *
 *   * `include/drm/drm.h` and `include/drm/virtgpu_drm.h`, straight out of the
 *     pinned libdrm checkout with NO PATCH APPLIED, are #included by a program
 *     built for x86_64-unknown-none-elf against core/user/libc;
 *   * every `DRM_IOCTL_*` request number in them is computed BY THE COMPILER,
 *     from `sizeof` of the structs as this target lays them out;
 *   * the program runs in ring 3 on this kernel and reports those numbers;
 *   * and `_IOC_DIR`/`_IOC_SIZE`/`_IOC_TYPE`/`_IOC_NR` decode them back.
 *
 * WHY THE HASH. There are DRMABI_COUNT (121, at the pinned commit) requests and
 * one printf per request would be 121 golden lines for a claim that is really
 * one claim. So the program folds all of them into an FNV-1a/32 over their
 * little-endian bytes and prints that, plus nine named requests chosen because
 * they are the ones the first four rungs of drm-abi.md's ladder actually issue.
 * run.sh recomputes the same hash on the host from a DIFFERENT toolchain and a
 * DIFFERENT copy of the headers. A single wrong struct size anywhere in the
 * uAPI moves the hash.
 *
 * THE NEGATIVE CONTROL IS BUILT FROM THIS SAME FILE, unchanged: build-progs.sh
 * puts a `sys/ioccom.h` carrying BSD's `_IOC` encoding ahead of ours on the
 * include path. `drm.h` takes its "one of the BSDs" branch on this target --
 * `__linux__` is not defined for x86_64-unknown-none-elf and this port does not
 * pretend otherwise -- so the encoding that header finds is entirely ours to
 * choose, and choosing wrong is silent. It changes 29 of the 121 request
 * numbers, DRM_IOCTL_GEM_CLOSE and DRM_IOCTL_SET_CLIENT_CAP and
 * DRM_IOCTL_SET_MASTER among them, and leaves the other 92 alone. The control
 * must produce a DIFFERENT hash and the SAME count.
 *
 * printf here has five conversions and a 120-byte cap (ADR-0017 §5), which is
 * why every line below is short and why nothing prints a 64-bit value: a DRM
 * request number is 32 bits and `%x` takes an `unsigned int`, exactly.
 */

#include "oslibc.h"

#include <stdint.h>

/* THE UNMODIFIED uAPI. Everything these two headers need arrives through
 * core/user/ports/libdrm/shim -- <sys/ioccom.h>, <sys/types.h>, <stdint.h> --
 * and `sys/ioccom.h` is where this port makes its one substantive choice: it
 * serves LINUX's _IOC encoding, not BSD's. ADR-0031 §3. */
#include "drm.h"
#include "virtgpu_drm.h"

/* GENERATED by gen-table.py: DRMABI_COUNT, drmabiVals[], drmabiNames[]. Every
 * entry of drmabiVals is `(unsigned int)DRM_IOCTL_<NAME>` and is therefore the
 * compiler's arithmetic, not the generator's. */
#include "table.h"

/* .data, not .bss: m19-argv's build check requires the R+W segment to have real
 * file bytes so the loader's copy path runs for it, and this program has no
 * other mutable global. */
volatile unsigned int drmabiMarker = 0x0D8A0001u;

/* S0 (ADR-0033). A word in `.rodata` — READABLE from ring 3, NOT WRITABLE —
 * for the `_IOC_READ` write-side negative control to aim at.
 *
 * IT HAS TO BE A SEPARATE OBJECT FROM `drmabiMarker`, WHICH IS NOT const AND
 * THEREFORE LIVES IN `.data`. Aiming the control at a writable page would make
 * it pass for the wrong reason — or rather, would make it FAIL to control
 * anything, because the write-side validator would correctly allow it.
 * `volatile const` rather than plain `const` so the compiler cannot fold it
 * away and leave the address pointing at nothing. */
volatile const unsigned int drmabiRoTarget = 0x0D8A0002u;

/* FNV-1a, 32-bit, over the little-endian bytes of every request number in
 * table order. Transcribed here and again in run.sh's python; the two are
 * independent implementations of a five-line function, which is the level of
 * duplication a checksum can carry without becoming its own oracle. */
static unsigned int fnv1a(const unsigned int *v, unsigned long n) {
  unsigned int h = 2166136261u;
  unsigned long i;
  for (i = 0; i < n; i++) {
    unsigned int x = v[i];
    unsigned int b;
    for (b = 0; b < 4; b++) {
      h ^= (x >> (b * 8)) & 0xFFu;
      h *= 16777619u;
    }
  }
  return h;
}

/* The nine requests drm-abi.md's R0-R3 rungs issue, named so that a moved hash
 * can be localised without a second boot. */
struct named {
  const char *name;
  unsigned int req;
};

int main(int argc, char **argv) {
  (void)argc;
  (void)argv;

  const struct named nine[9] = {
      {"VERSION", (unsigned int)DRM_IOCTL_VERSION},
      {"GET_CAP", (unsigned int)DRM_IOCTL_GET_CAP},
      {"SET_CLIENT_CAP", (unsigned int)DRM_IOCTL_SET_CLIENT_CAP},
      {"GEM_CLOSE", (unsigned int)DRM_IOCTL_GEM_CLOSE},
      {"PRIME_HANDLE_TO_FD", (unsigned int)DRM_IOCTL_PRIME_HANDLE_TO_FD},
      {"MODE_CREATE_DUMB", (unsigned int)DRM_IOCTL_MODE_CREATE_DUMB},
      {"MODE_MAP_DUMB", (unsigned int)DRM_IOCTL_MODE_MAP_DUMB},
      {"MODE_ADDFB2", (unsigned int)DRM_IOCTL_MODE_ADDFB2},
      {"VIRTGPU_EXECBUFFER", (unsigned int)DRM_IOCTL_VIRTGPU_EXECBUFFER},
  };

  printf("DRMABI START marker=%x", drmabiMarker);
  printf("DRMABI COUNT %d", (int)DRMABI_COUNT);
  printf("DRMABI HASH %x", fnv1a(drmabiVals, (unsigned long)DRMABI_COUNT));

  int i;
  for (i = 0; i < 9; i++) {
    printf("DRMABI REQ %s %x", nine[i].name, nine[i].req);
  }

  /* THE DECODE. A kernel serving this ABI must pull four fields out of the
   * request word; this proves the encoding those four fields were packed into
   * is the one this program's headers produced. `_IOC_TYPE` is printed as a
   * character as well as a number because 0x64 being 'd' is the whole of what
   * "the DRM ioctl group" means. */
  for (i = 0; i < 9; i++) {
    unsigned int r = nine[i].req;
    printf("DRMABI DEC %s dir=%d size=%d type=%c nr=%d", nine[i].name,
           (int)_IOC_DIR(r), (int)_IOC_SIZE(r), (char)_IOC_TYPE(r),
           (int)_IOC_NR(r));
  }

  /* THE STRUCT SIZES, separately from the request numbers that encode them.
   * `_IOC_SIZE` is 14 bits wide, so a struct of 16384 bytes or more would wrap
   * silently; printing sizeof alongside the encoded size is what makes the two
   * checkable against each other rather than against themselves. */
  printf("DRMABI SZ version=%d get_cap=%d set_client_cap=%d",
         (int)sizeof(struct drm_version), (int)sizeof(struct drm_get_cap),
         (int)sizeof(struct drm_set_client_cap));
  printf("DRMABI SZ gem_close=%d prime_handle=%d unique=%d",
         (int)sizeof(struct drm_gem_close), (int)sizeof(struct drm_prime_handle),
         (int)sizeof(struct drm_unique));
  printf("DRMABI SZ create_dumb=%d map_dumb=%d destroy_dumb=%d",
         (int)sizeof(struct drm_mode_create_dumb),
         (int)sizeof(struct drm_mode_map_dumb),
         (int)sizeof(struct drm_mode_destroy_dumb));
  printf("DRMABI SZ fb_cmd2=%d crtc=%d atomic=%d",
         (int)sizeof(struct drm_mode_fb_cmd2), (int)sizeof(struct drm_mode_crtc),
         (int)sizeof(struct drm_mode_atomic));
  printf("DRMABI SZ vg_execbuf=%d vg_map=%d vg_res_create=%d",
         (int)sizeof(struct drm_virtgpu_execbuffer),
         (int)sizeof(struct drm_virtgpu_map),
         (int)sizeof(struct drm_virtgpu_resource_create));
  printf("DRMABI SZ event=%d event_vblank=%d syncobj_handle=%d",
         (int)sizeof(struct drm_event), (int)sizeof(struct drm_event_vblank),
         (int)sizeof(struct drm_syncobj_handle));

  /* THE ENCODED SIZE IS THE STRUCT SIZE, asserted by the program against
   * `sizeof` for every one of the nine rather than left to a reader to compare
   * two printed columns. This is the property drm-abi.md §2.1 says a kernel
   * must not get wrong: the size is IN the request number, so a struct whose
   * layout differs from Linux's changes the number silently. */
  int szmatch = 0;
  const unsigned int nineSz[9] = {
      (unsigned int)sizeof(struct drm_version),
      (unsigned int)sizeof(struct drm_get_cap),
      (unsigned int)sizeof(struct drm_set_client_cap),
      (unsigned int)sizeof(struct drm_gem_close),
      (unsigned int)sizeof(struct drm_prime_handle),
      (unsigned int)sizeof(struct drm_mode_create_dumb),
      (unsigned int)sizeof(struct drm_mode_map_dumb),
      (unsigned int)sizeof(struct drm_mode_fb_cmd2),
      (unsigned int)sizeof(struct drm_virtgpu_execbuffer),
  };
  for (i = 0; i < 9; i++) {
    if (_IOC_SIZE(nine[i].req) == nineSz[i]) {
      szmatch++;
    }
  }
  printf("DRMABI SIZEENC %d of 9", szmatch);

  /* Two whole-table numbers the host can predict exactly: how many requests
   * carry no payload at all (`_IO`, which is what SET_MASTER and DROP_MASTER
   * are, and which the BSD encoding gets wrong in a way that is invisible in
   * every other field), and the largest payload any of them carries -- against
   * the 14-bit ceiling `_IOC_SIZE` imposes. */
  int zerosz = 0;
  unsigned int maxsz = 0;
  unsigned int i2;
  for (i2 = 0; i2 < (unsigned int)DRMABI_COUNT; i2++) {
    unsigned int s = _IOC_SIZE(drmabiVals[i2]);
    if (s == 0u) {
      zerosz++;
    }
    if (s > maxsz) {
      maxsz = s;
    }
  }
  printf("DRMABI ZEROSIZE %d MAXSIZE %d CEIL %d", zerosz, (int)maxsz, 16383);

  /* =====================================================================
   * S0 (ADR-0033) — THE IOCTL ITSELF, AND THE FOUR NEGATIVE CONTROLS.
   *
   * Everything above this line runs on a kernel with no `ioctl` and is
   * unchanged. Everything below issues real syscall 12s against a real
   * device descriptor.
   *
   * **EVERY REQUEST WORD BELOW IS BUILT BY THE `_IOC` MACROS FROM LIBDRM'S
   * UNMODIFIED uAPI HEADERS**, exactly as the nine above are -- not typed as
   * a hex literal. That is what makes the comparison with the kernel's decode
   * a comparison of two independent computations rather than of a number with
   * itself. ADR-0031 §4.4 requires precisely this.
   *
   * The negative controls are the point of the unit, so each one PRINTS THE
   * REFUSAL IT OBSERVED rather than a pass/fail verdict: the harness compares
   * the observed value against a value it derives itself, and a control that
   * printed "ok" would be the program grading its own homework.
   * ===================================================================== */

  {
    unsigned long fd;
    unsigned long r;
    /* The payload buffer. `volatile` so the compiler cannot decide that a
     * buffer the kernel writes through a pointer is dead. 64 bytes is
     * DRM_IOCTL_VERSION's `_IOC_SIZE`, which is the largest thing sent. */
    static volatile unsigned char payload[64];
    unsigned int k;

    /* ---- open the device. ADR-0031 §6: the name is LITERAL. ---- */
    fd = openmode("/dev/dri/card0", O_READ);
    printf("DRMABI DEVOPEN fd=%x", (unsigned int)fd);

    /* A name in the device namespace that is not a device this kernel
     * serves. Must be FILE_ENOTFOUND and must NOT be attempted as an 8.3
     * FAT name -- a `/` name reaching fatParseAt would be EBADNAME. */
    r = openmode("/dev/dri/card9", O_READ);
    printf("DRMABI DEVMISS %x", (unsigned int)r);

    if (fd < FILE_ERR_FLOOR) {
      /* ---- R0: the real thing. _IOWR('d', 0x00, struct drm_version). ----
       * Seeded so the out-copy is distinguishable from "the buffer was
       * already right". */
      for (k = 0; k < 64; k++) {
        payload[k] = 0xA5;
      }
      r = os_ioctl(fd, (unsigned long)DRM_IOCTL_VERSION, (void *)payload);
      printf("DRMABI IOCTL VERSION ret=%x b0=%x b63=%x", (unsigned int)r,
             (unsigned int)payload[0], (unsigned int)payload[63]);

      /* ---- _IOC_NONE: a request with no payload at all, and argp NULL.
       * Four of the 121 are like this and a kernel that assumed a payload
       * would refuse it. ---- */
      r = os_ioctl(fd, (unsigned long)DRM_IOCTL_SET_MASTER, (void *)0);
      printf("DRMABI IOCTL SET_MASTER ret=%x", (unsigned int)r);

      /* ---- _IOC_WRITE only: userspace writes, the kernel reads. The
       * out-direction byte count must be ZERO, which is the anti-vacuity
       * check ADR-0031 §4.4 asks for -- a kernel ignoring _IOC_DIR would
       * copy both ways and the IN/OUT counts would match. ---- */
      for (k = 0; k < 8; k++) {
        payload[k] = 0x5C;
      }
      r = os_ioctl(fd, (unsigned long)DRM_IOCTL_GEM_CLOSE, (void *)payload);
      printf("DRMABI IOCTL GEM_CLOSE ret=%x b0=%x", (unsigned int)r,
             (unsigned int)payload[0]);

      /* ---- THE VERSION-SKEW ROW. The SAME nr, TWO legal sizes.
       * libdrm 2.4.134 says 24 bytes; Linux 6.12 says 16. Both must be
       * served, and they differ ONLY in _IOC_SIZE -- so a kernel that
       * switched on the whole request word serves exactly one of them.
       * The second request is built by hand from the FIELDS, which is the
       * only way to express "the same request, an older struct". ---- */
      r = os_ioctl(fd, (unsigned long)DRM_IOCTL_SYNCOBJ_HANDLE_TO_FD,
                   (void *)payload);
      printf("DRMABI IOCTL SYNCOBJ24 ret=%x", (unsigned int)r);
      r = os_ioctl(fd, (unsigned long)_IOC(IOC_INOUT, 'd', 0xC1, 16),
                   (void *)payload);
      printf("DRMABI IOCTL SYNCOBJ16 ret=%x", (unsigned int)r);

      /* =================================================================
       * NEGATIVE CONTROL 1 — AN OVERSIZED PAYLOAD MUST BE REFUSED, NOT
       * TRUNCATED.
       *
       * 4096 bytes is far above IOCTL_MAX_PAYLOAD (256) and far below the
       * encoding's 14-bit ceiling (16383), so this is a request the ENCODING
       * permits and the KERNEL must not. A truncating kernel would return 0
       * having copied 256 bytes, and the caller would have no way to notice.
       * ================================================================= */
      r = os_ioctl(fd, (unsigned long)_IOC(IOC_INOUT, 'd', 0x00, 4096),
                   (void *)payload);
      printf("DRMABI NEG OVERSIZE ret=%x", (unsigned int)r);

      /* =================================================================
       * NEGATIVE CONTROL 2 — A WRONG-SIZE REQUEST MUST BE REFUSED, NOT
       * ZERO-EXTENDED.
       *
       * nr 0x00 is VERSION and this kernel serves it at exactly 64 bytes.
       * 48 is a legal _IOC_SIZE, is under IOCTL_MAX_PAYLOAD, and is not in
       * the descriptor's set. Linux's policy for a short struct is to
       * zero-extend; ours is to refuse, because zero-extending by default is
       * how a caller's uninitialised field becomes a kernel default nobody
       * chose (design/libdrm-port.md §5).
       * ================================================================= */
      r = os_ioctl(fd, (unsigned long)_IOC(IOC_INOUT, 'd', 0x00, 48),
                   (void *)payload);
      printf("DRMABI NEG WRONGSIZE ret=%x", (unsigned int)r);

      /* =================================================================
       * NEGATIVE CONTROL 3 — AN `argp` OUTSIDE THE PROCESS MUST BE REFUSED.
       *
       * A KERNEL ADDRESS, chosen the same way m9-ring3's payload chooses
       * one. The kernel copies with kernel privilege, so a `memcpy` into an
       * address ring 3 named is a write ring 3 could not have performed
       * itself -- this is the hole the whole of §4.3 rule 4 exists to close,
       * and it must be closed IN SOFTWARE: GAP-0153 records that SMEP's bit
       * is set and that nothing on this machine proves it blocks anything.
       * ================================================================= */
      r = os_ioctl(fd, (unsigned long)DRM_IOCTL_VERSION, (void *)0x100000UL);
      printf("DRMABI NEG BADPTR ret=%x", (unsigned int)r);

      /* And a pointer that is inside the program's window but whose range
       * RUNS OFF THE END of a mapped page -- GAP-0124's case, which is why
       * elfOwns walks every page rather than the first. */
      r = os_ioctl(fd, (unsigned long)DRM_IOCTL_VERSION,
                   (void *)((unsigned long)payload + 0x3FE000UL));
      printf("DRMABI NEG FARPTR ret=%x", (unsigned int)r);

      /* =================================================================
       * NEGATIVE CONTROL 4 — A WRITE-SIDE VIOLATION ON `_IOC_READ` MUST BE
       * REFUSED.
       *
       * **THIS IS THE ONE THAT CATCHES THE DIRECTIONS BEING SWAPPED**, and
       * it is invisible on all 92 `_IOWR` requests. GET_MAGIC is `_IOC_READ`
       * only: the KERNEL writes and userspace reads. So `argp` must pass the
       * WRITE-side validator -- and this aims it at the program's own
       * `.rodata`, which ring 3 may read and may not write.
       *
       * A kernel with the directions backwards would run the READ-side
       * validator here, pass, and then write to a read-only page.
       * `drmabiRoTarget` is a `volatile const` and lives in .rodata;
       * m15-fileio aims a `read` at exactly the same kind of target for
       * exactly this reason. `drmabiMarker` would NOT do: it is not const,
       * so it is in .data and ring 3 may write it.
       * ================================================================= */
      r = os_ioctl(fd, (unsigned long)DRM_IOCTL_GET_MAGIC,
                   (void *)&drmabiRoTarget);
      printf("DRMABI NEG RODATA ret=%x", (unsigned int)r);

      /* **THE `_IOWR` CONTROL THAT DISTINGUISHES "BOTH VALIDATORS" FROM
       * "THE READ-SIDE ONE".** ADR-0033 §4.3 rule 4 says an _IOWR runs BOTH,
       * and the two controls above do not prove it: they aim at addresses
       * that fail the READ-side validator too, so a kernel running only the
       * read side refuses them for the right-looking reason.
       *
       * THIS WAS FOUND BY MUTATION AND NOT BY READING. Deleting the
       * write-side call from the _IOWR arm left the whole suite GREEN.
       * `.rodata` is the discriminator: ring 3 may read it, so the read-side
       * validator PASSES, and the kernel is about to write there. */
      r = os_ioctl(fd, (unsigned long)DRM_IOCTL_VERSION,
                   (void *)&drmabiRoTarget);
      printf("DRMABI NEG IOWRRO ret=%x", (unsigned int)r);

      /* And the same request aimed at writable memory, which MUST succeed --
       * otherwise the control above would pass for the wrong reason (a
       * kernel that refused every _IOC_READ). */
      r = os_ioctl(fd, (unsigned long)DRM_IOCTL_GET_MAGIC, (void *)payload);
      printf("DRMABI POS RODATACTL ret=%x b0=%x", (unsigned int)r,
             (unsigned int)payload[0]);

      /* ---- A type this kernel does not serve. Checked FIRST, before any
       * other field, so this must be EBADTYPE and not EBADNR. ---- */
      r = os_ioctl(fd, (unsigned long)_IOC(IOC_INOUT, 'z', 0x00, 64),
                   (void *)payload);
      printf("DRMABI NEG BADTYPE ret=%x", (unsigned int)r);

      /* ---- A DRM nr this kernel does not serve. ---- */
      r = os_ioctl(fd, (unsigned long)_IOC(IOC_INOUT, 'd', 0x7E, 64),
                   (void *)payload);
      printf("DRMABI NEG BADNR ret=%x", (unsigned int)r);

      os_close(fd);
    }

    /* ---- ioctl on a FAT16 FILE must be ENOTTY's equivalent, and must be a
     * DISTINCT value from every file.dart refusal (ADR-0031 §4.3 rule 7). ---- */
    {
      unsigned long ffd = openmode("README.TXT", O_READ);
      if (ffd < FILE_ERR_FLOOR) {
        r = os_ioctl(ffd, (unsigned long)DRM_IOCTL_VERSION, (void *)payload);
        printf("DRMABI NEG NOTDEV ret=%x", (unsigned int)r);
        os_close(ffd);
      } else {
        printf("DRMABI NEG NOTDEV noopen=%x", (unsigned int)ffd);
      }
    }

    /* ---- ioctl on a descriptor that was never opened. ---- */
    r = os_ioctl(3, (unsigned long)DRM_IOCTL_VERSION, (void *)payload);
    printf("DRMABI NEG BADFD ret=%x", (unsigned int)r);
  }

  printf("DRMABI DONE");
  return 0;
}
