#!/usr/bin/env python3
"""core/tests/conformance/d2-compositor/derive.py

Computes, ON THE HOST AND BEFORE ANY BOOT, exactly what must be on the screen.

WHAT IT DERIVES FROM, AND WHY THAT IS THE WHOLE POINT
---------------------------------------------------------------------------
Nothing in this file is a number somebody typed twice. Every expectation is
computed from constants read out of the source of the thing being tested:

  prog.c        the two surfaces' geometry, their four colours, the inset of
                the inner block, and the page count
  wm.dart       the desktop colour, the border width, and the two border
                colours -- so a compositor whose palette changed produces a
                DIFFERENT expected image and the harness says which pixel
  mouse.dart    the cursor's two 16x12 bitmaps and its two colours, and the
                delta span the PS/2 decoder uses -- so the cursor assertion is
                against the arrow this kernel actually draws
  the event     the pointer script, decoded with QEMU's axis convention and the
  script        kernel's own clamping

If any of those move, this file's output moves with them and the harness keeps
meaning what it says. That is the property `m21-shmem/derive.py` and
`d1-mouse/derive.py` are built for, and it is why the expectations are not
checked in as a golden image: a golden PNG would have to be regenerated by
running the thing it is supposed to be testing.

THE ONE EXPECTATION THAT MUST FAIL
---------------------------------------------------------------------------
`control=` is a probe with the WRONG colour on purpose -- the BOTTOM window's
fill, at a coordinate inside the overlap where the TOP window's fill is what is
actually there. `run.sh` asserts it and REQUIRES the assertion to fail. A
compositor that ignored stacking order would satisfy the ordinary probes for one
of the two windows and could never satisfy both this and probe `b_overlap`,
which is the whole of D5's negative control as `display-protocol.md` s6 states
it: "swap the stacking order and require the previous expectation to fail".

    derive.py <prog.c> <wm.dart> <mouse.dart> <event-script> <drag-script>

Exit status: 0 and `key=value` lines on stdout, 2 on a derivation failure.
"""

import re
import sys


def die(msg):
    print("derive: " + msg, file=sys.stderr)
    raise SystemExit(2)


def c_defs(path):
    """`#define NAME VALUE` out of a C source, values as ints."""
    out = {}
    for m in re.finditer(r"^#define\s+([A-Z_0-9]+)\s+(0[xX][0-9A-Fa-f]+|\d+)U?L?$",
                         open(path).read(), re.M):
        out[m.group(1)] = int(m.group(2), 0)
    return out


def dart_ints(path):
    """`const int name = value;` out of a DCDart source."""
    out = {}
    for m in re.finditer(r"^const int (\w+) = (0[xX][0-9A-Fa-f]+|\d+);$",
                         open(path).read(), re.M):
        out[m.group(1)] = int(m.group(2), 0)
    return out


def dart_table(path, name):
    """A `@rodata final List<u8> name = const [...]` as a list of ints."""
    m = re.search(r"final List<u8> %s = const \[(.*?)\];" % name,
                  open(path).read(), re.S)
    if not m:
        die("no @rodata table %r in %s" % (name, path))
    return [int(x, 16) for x in re.findall(r"u8\(0x([0-9A-Fa-f]{2})\)", m.group(1))]


def main():
    if len(sys.argv) != 6:
        die("usage: derive.py <prog.c> <wm.dart> <mouse.dart> <event-script> "
            "<drag-script>")
    progc, wmdart, mousedart, events, dragscript = sys.argv[1:6]

    P = c_defs(progc)
    W = dart_ints(wmdart)
    M = dart_ints(mousedart)
    for k in ("WIN_W", "WIN_H", "A_X", "A_Y", "B_X", "B_Y", "A_FILL", "A_INK",
              "B_FILL", "B_INK", "INK_INSET", "WIN_PAGES", "HOLDSPIN",
              "DMG_X", "DMG_Y", "DMG_W", "DMG_H", "DMG_INK"):
        if k not in P:
            die("prog.c does not define %s" % k)
    for k in ("wmColorDesktop", "wmBorder", "wmColorFocus", "wmColorUnfocus",
              "wmMaxWindows", "wmSysSurfaceNo"):
        if k not in W:
            die("wm.dart does not define %s" % k)

    w, h = P["WIN_W"], P["WIN_H"]
    inset = P["INK_INSET"]
    b = W["wmBorder"]
    fbw, fbh = 800, 600

    # --- the page count must actually hold the surface ---------------------
    need_pages = (w * h * 4 + 4095) // 4096
    if P["WIN_PAGES"] != need_pages:
        die("prog.c asks for %d pages but %dx%d at 4 bytes per pixel needs %d; "
            "the kernel would refuse the attach with wmRetSmall and the harness "
            "should say which of the two numbers is wrong"
            % (P["WIN_PAGES"], w, h, need_pages))

    # --- the two windows must actually overlap -----------------------------
    # If they did not, D5 would be vacuous: two disjoint rectangles are composed
    # correctly by any order at all.
    ox0, ox1 = max(P["A_X"], P["B_X"]), min(P["A_X"] + w, P["B_X"] + w)
    oy0, oy1 = max(P["A_Y"], P["B_Y"]), min(P["A_Y"] + h, P["B_Y"] + h)
    if ox0 >= ox1 or oy0 >= oy1:
        die("the two surfaces do not overlap -- the stacking-order assertion "
            "would be vacuous")

    def surface_base(side, px, py):
        ink = (inset <= px < w - inset) and (inset <= py < h - inset)
        if side == 0:
            return P["A_INK"] if ink else P["A_FILL"]
        return P["B_INK"] if ink else P["B_FILL"]

    dmg_x, dmg_y = P["DMG_X"], P["DMG_Y"]
    dmg_w, dmg_h = P["DMG_W"], P["DMG_H"]
    dmg_ink = P["DMG_INK"]
    if dmg_w < 1 or dmg_h < 1:
        die("the D6 damage rectangle is empty -- the small-count assertion "
            "would be a number with no pixels behind it")
    if dmg_x + dmg_w > w or dmg_y + dmg_h > h:
        die("the D6 damage rectangle does not fit the surface; the kernel "
            "would refuse the commit with wmRetBadGeom")
    # Every overwritten pixel must actually change colour, otherwise a
    # compositor that ignored the second commit would still match the probe.
    overwritten = 0
    for py in range(dmg_h):
        for px in range(dmg_w):
            if surface_base(1, dmg_x + px, dmg_y + py) == dmg_ink:
                die("D6 patch pixel (%d,%d) is already the damage colour; the "
                    "probe cannot tell a present from a skip" % (px, py))
            overwritten += 1
    if overwritten != dmg_w * dmg_h:
        die("internal: damage area is %d, counted %d" % (dmg_w * dmg_h, overwritten))

    def surface_pixel(side, px, py):
        """The surface AFTER side 1's D6 present. Phase-1 and phase-2 probes
        both read this: the first dump is taken after that commit."""
        if side == 1 and dmg_x <= px < dmg_x + dmg_w and dmg_y <= py < dmg_y + dmg_h:
            return dmg_ink
        return surface_base(side, px, py)

    # --- what each client exits with ---------------------------------------
    sums = []
    for side in (0, 1):
        s = 0
        for py in range(h):
            for px in range(w):
                s += surface_base(side, px, py)
        sums.append(s)
    # Side 1 overwrites the patch after the first paint. The exit sum is the
    # first paint plus the net delta, which is what paint_damage returns.
    delta = 0
    for py in range(dmg_h):
        for px in range(dmg_w):
            delta += dmg_ink - surface_base(1, dmg_x + px, dmg_y + py)
    sums[1] += delta
    # exit = (side << 56) | (frames_at_last_commit << 48) | (sum & 2**48-1)
    # `wm on` is frame 1, A's full-surface commit is 2, B's full-surface is 3,
    # B's 16x16 is 4.
    exit_a = (0 << 56) | (2 << 48) | (sums[0] & 0xFFFFFFFFFFFF)
    exit_b = (1 << 56) | (4 << 48) | (sums[1] & 0xFFFFFFFFFFFF)

    # --- pixels composed per frame -----------------------------------------
    # D6: a commit paints the damage, not the desktop. Full-surface damage is
    # the decorated window (border included). A 16x16 is 256.
    decorated = (w + 2 * b) * (h + 2 * b)
    px1 = fbw * fbh
    px2 = decorated
    # B's first present is a full-surface commit of the NEW top window, so
    # the compositor also repaints A -- otherwise A's border stays bright
    # and D5's stacking probe has no dim colour to find.
    px3 = 2 * decorated
    px4 = dmg_w * dmg_h
    if px4 >= px2:
        die("the D6 damage rectangle is %d pixels and a decorated window is "
            "%d -- the small-count assertion cannot tell damage from a "
            "window-sized fallback" % (px4, px2))
    if px2 >= px1:
        die("a decorated window is %d pixels and the desktop is %d -- a "
            "commit that fell back to a full frame would not be distinguishable"
            % (px2, px1))

    # --- the pointer -------------------------------------------------------
    #
    # QEMU's convention: +x moves right and arrives as `mouse_dx += v`; +y moves
    # DOWN and arrives as `mouse_dy -= v`, because a PS/2 mouse reports Y
    # positive upward. `mouseApplyY` sees the sign bit and does
    # `y += (mouseDeltaSpan - b2)`, which for an injected +v is `y += v`. The
    # kernel clamps both axes to the visible area.
    span = M.get("mouseDeltaSpan", 256)

    def script(path):
        """`rel <dx> <dy>` / `grab` / `drop`, comments and blanks stripped."""
        out = []
        for line in open(path):
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            if line in ("grab", "drop"):
                out.append((line, 0, 0))
                continue
            mm = re.match(r"^rel\s+(-?\d+)\s+(-?\d+)$", line)
            if not mm:
                die("script line %r is not `rel <dx> <dy>`, `grab` or `drop`"
                    % line)
            dx, dy = int(mm.group(1)), int(mm.group(2))
            # A PS/2 packet carries a 9-bit signed delta and QEMU's own device
            # model clamps before the guest ever sees it, so a step this harness
            # cannot predict is a step it must refuse to derive.
            if not (0 < abs(dx) < span // 2) or not (0 < abs(dy) < span // 2):
                die("event `rel %d %d` is outside the range one PS/2 packet "
                    "carries unambiguously (1..%d on each axis)"
                    % (dx, dy, span // 2 - 1))
            out.append(("rel", dx, dy))
        return out

    def move(cx, cy, dx, dy):
        """`mouseApplyX`/`mouseApplyY`, including their clamps. QEMU's +y is
        DOWN the screen and reaches the guest as a NEGATIVE PS/2 delta, which
        `mouseApplyY` turns back into `y += v` -- so the two sign flips cancel
        and this is a plain addition. The clamps are the kernel's."""
        return (max(0, min(cx + dx, fbw - 1)), max(0, min(cy + dy, fbh - 1)))

    cx = cy = 0
    nrel = 0
    for kind, dx, dy in script(events):
        if kind != "rel":
            die("the phase-1 script must contain motions only; `%s` belongs in "
                "the drag script" % kind)
        cx, cy = move(cx, cy, dx, dy)
        nrel += 1
    if nrel == 0:
        die("the event script moves the pointer nowhere; the cursor assertion "
            "would be at (0,0), on top of nothing, and would prove nothing")

    # --- the cursor's own pixels, out of the kernel's own bitmaps ----------
    edge = dart_table(mousedart, "mouseCursorEdge")
    fill = dart_table(mousedart, "mouseCursorFill")
    rows = M["mouseCursorRows"]
    cols = M["mouseCursorCols"]
    edge_c = M["mouseCursorEdgeColor"]
    fill_c = M["mouseCursorFillColor"]

    def bits(tab, row):
        return (tab[row * 2] << 8) | tab[row * 2 + 1]

    def cursor_at(col, row):
        """None if the arrow does not cover (col,row); else its colour. Fill is
        blitted AFTER edge, so fill wins where both are set -- which is what
        `mouseDrawCursor` does and is the only place the order matters."""
        if bits(fill, row) & (1 << (15 - col)):
            return fill_c
        if bits(edge, row) & (1 << (15 - col)):
            return edge_c
        return None

    cur_edge = cur_fill = cur_clear = None
    for row in range(rows):
        for col in range(cols):
            c = cursor_at(col, row)
            if c == edge_c and cur_edge is None:
                cur_edge = (col, row)
            if c == fill_c and cur_fill is None:
                cur_fill = (col, row)
            if c is None and cur_clear is None:
                cur_clear = (col, row)
    if cur_edge is None or cur_fill is None or cur_clear is None:
        die("the cursor bitmaps do not contain all three of an edge pixel, a "
            "fill pixel and a clear pixel; the cursor assertion cannot be made")

    # --- the probes ---------------------------------------------------------
    #
    # Every one is a (x, y, colour, name). They are COMPUTED from the geometry
    # above, never typed, so moving a window in prog.c moves the probes with it.
    probes = []

    def under_pointer(px, py, ptr):
        """The arrow's 12x16 bounding box. **Not its set pixels**: a probe
        anywhere in the box is a probe whose value depends on the cursor
        bitmap, and a model that did not draw the arrow would be predicting the
        window underneath it. This exists because the first version of the
        phase-2 probes put the moved window's inner block at the exact
        coordinate the pointer ended on, and read back the arrow's black edge."""
        return (ptr[0] <= px < ptr[0] + cols) and (ptr[1] <= py < ptr[1] + rows)

    def add(name, x, y, colour, over_pointer=False):
        if not (0 <= x < fbw and 0 <= y < fbh):
            die("probe %s at (%d,%d) is off the screen" % (name, x, y))
        if not over_pointer and under_pointer(x, y, (cx, cy)):
            die("probe %s at (%d,%d) is inside the pointer's 12x16 box at "
                "(%d,%d); what is there is the arrow, not the window, and this "
                "model does not draw the arrow" % (name, x, y, cx, cy))
        probes.append((name, x, y, colour))

    ax, ay, bx, by = P["A_X"], P["A_Y"], P["B_X"], P["B_Y"]

    # 1. the desktop, well away from both windows and from the pointer
    dx_, dy_ = 40, fbh - 40
    add("desktop", dx_, dy_, W["wmColorDesktop"])

    # 2. window A's fill, outside its inner block and outside the overlap
    add("a_fill", ax + inset // 2, ay + inset // 2, P["A_FILL"])
    # 3. window A's inner block, outside the overlap
    add("a_ink", ax + inset + 10, ay + inset + 10, P["A_INK"])
    # 4. window A's border -- DIM, because A is not on top
    add("a_border", ax - 1, ay + inset, W["wmColorUnfocus"])

    # 5. window B's fill INSIDE THE OVERLAP. This is D5: A is underneath here.
    add("b_overlap", ox0 + 5, oy0 + 5, P["B_FILL"])
    # 6. window B's inner block, also inside the overlap where one exists
    bix, biy = bx + inset, by + inset
    if ox0 <= bix < ox1 and oy0 <= biy < oy1:
        add("b_ink_overlap", bix + 2, biy + 2, P["B_INK"])
    else:
        add("b_ink", bix + 2, biy + 2, P["B_INK"])
    # 7. window B's border -- BRIGHT, because B attached second and is on top.
    #    At this coordinate A's own content is what would be there without a
    #    compositor that stacks, so this probe is a second stacking assertion.
    add("b_border", bx - 1, oy0 + 5, W["wmColorFocus"])
    # 8. window A's top border
    add("a_border_top", ax + inset, ay - 1, W["wmColorUnfocus"])
    # 8b. D6: the 16x16 patch on B, after the second commit. Centre of the
    #     rectangle, so a compositor that painted a single pixel or the
    #     wrong origin cannot satisfy it.
    add("b_damage", bx + dmg_x + dmg_w // 2, by + dmg_y + dmg_h // 2, dmg_ink)

    # 9. the pointer, drawn on top of the desktop
    add("cursor_edge", cx + cur_edge[0], cy + cur_edge[1], edge_c, True)
    add("cursor_fill", cx + cur_fill[0], cy + cur_fill[1], fill_c, True)
    add("cursor_clear", cx + cur_clear[0], cy + cur_clear[1], W["wmColorDesktop"],
        True)

    # --- THE CONTROL. The bottom window's fill, where the top window's is. ---
    control = ("control_bottom_in_overlap", ox0 + 5, oy0 + 5, P["A_FILL"])
    if control[3] == P["B_FILL"]:
        die("the two surfaces' fills are the same colour; the stacking control "
            "cannot tell the two apart and is testing nothing")

    # ======================================================================
    # PHASE 2 -- THE DRAG, SIMULATED ON THE HOST AGAINST THE SAME RULES
    # ======================================================================
    #
    # This is a MODEL of `wmGrab`/`wmDragStep`, not a transcript of them: the
    # hit test, the grab offset, the clamp and the resulting origin are all
    # recomputed here from the geometry above. A kernel that grabbed the wrong
    # window, used the pointer instead of the grab offset (so the window jumped),
    # or clamped differently produces a different origin and the harness says so.
    #
    # PHASE 1's POINTER POSITION IS SAVED FIRST. `cx`/`cy` are about to become
    # the phase-2 pointer, and the phase-1 cursor probes were computed from them
    # above -- printing the mutated pair as `cursor_x`/`cursor_y` would have the
    # transcript assertion disagree with the pixel assertions it sits next to.
    p1cx, p1cy = cx, cy
    windows = {0: [P["A_X"], P["A_Y"]], 1: [P["B_X"], P["B_Y"]]}
    top = 1          # B attached second, so B is on top when phase 2 begins
    drag = None
    grab = (0, 0)
    raises = []
    moves = 0

    def covers(i, px, py):
        """`wmWindowPixel != wmNoPixel` -- the DECORATED rectangle, border
        included, because that is what `wmHit` tests."""
        ox, oy = windows[i]
        return (ox - b <= px < ox + w + b) and (oy - b <= py < oy + h + b)

    def hit(px, py):
        if covers(top, px, py):
            return top
        for i in sorted(windows):
            if i != top and covers(i, px, py):
                return i
        return None

    def clamp(ox, oy):
        return (max(b, min(ox, fbw - b - w)), max(b, min(oy, fbh - b - h)))

    for kind, dx, dy in script(dragscript):
        if kind == "rel":
            cx, cy = move(cx, cy, dx, dy)
            if drag is not None:
                ox, oy = clamp(cx - grab[0], cy - grab[1])
                if [ox, oy] != windows[drag]:
                    windows[drag] = [ox, oy]
                    moves += 1
        elif kind == "grab":
            tgt = hit(cx, cy)
            if tgt is None:
                die("the drag script presses the button at (%d,%d), which is "
                    "over no window -- there would be nothing to raise and "
                    "nothing to move" % (cx, cy))
            drag = tgt
            grab = (cx - windows[tgt][0], cy - windows[tgt][1])
            if tgt != top:
                raises.append((top, tgt))
                top = tgt
        else:
            drag = None
    if moves == 0:
        die("the drag script moves no window; the whole of phase 2 would be "
            "asserting that nothing happened")
    if not raises:
        die("the drag script never raises a window -- it clicks the one that is "
            "already on top, so the stacking half of phase 2 is vacuous")

    ax2, ay2 = windows[0]
    bx2, by2 = windows[1]
    if (ax2, ay2) == (P["A_X"], P["A_Y"]):
        die("the dragged window ends where it started; the move assertion would "
            "be satisfied by a compositor that ignored the pointer")

    def pixel_at(px, py):
        """`wmPixelAt` on the host: the topmost window covering the pixel, or
        the desktop. Content, border and desktop, in that resolution order."""
        order = [top] + [i for i in sorted(windows) if i != top]
        for i in order:
            if not covers(i, px, py):
                continue
            ox, oy = windows[i]
            if ox <= px < ox + w and oy <= py < oy + h:
                return surface_pixel(i, px - ox, py - oy)
            return W["wmColorFocus"] if i == top else W["wmColorUnfocus"]
        return W["wmColorDesktop"]

    # The overlap AFTER the drag, which is where "the raise actually changed
    # which window is on top" is a pixel.
    o2x0, o2x1 = max(ax2, bx2), min(ax2 + w, bx2 + w)
    o2y0, o2y1 = max(ay2, by2), min(ay2 + h, by2 + h)
    if o2x0 >= o2x1 or o2y0 >= o2y1:
        die("after the drag the two surfaces no longer overlap, so the raise "
            "cannot be asserted as a pixel")
    RAISED = (o2x0 + 40, o2y0 + 30)

    # THE SAME COORDINATE IS PROBED IN BOTH DUMPS. Before the raise it must hold
    # the colour of the window that was on top; after it, the colour of the one
    # that now is. Two positive assertions about one pixel, which is a stronger
    # statement than either alone and is what makes the phase-2 control mean
    # something.
    before_at_raised = None
    for i in (1, 0):   # B on top in phase 1, then A
        ox, oy = (P["B_X"], P["B_Y"]) if i == 1 else (P["A_X"], P["A_Y"])
        if ox - b <= RAISED[0] < ox + w + b and oy - b <= RAISED[1] < oy + h + b:
            if ox <= RAISED[0] < ox + w and oy <= RAISED[1] < oy + h:
                before_at_raised = surface_pixel(i, RAISED[0] - ox, RAISED[1] - oy)
            else:
                before_at_raised = W["wmColorFocus"] if i == 1 else W["wmColorUnfocus"]
            break
    if before_at_raised is None:
        before_at_raised = W["wmColorDesktop"]
    after_at_raised = pixel_at(RAISED[0], RAISED[1])
    if before_at_raised == after_at_raised:
        die("the raise probe at (%d,%d) is the same colour before and after; it "
            "cannot see the stacking order change" % RAISED)

    probes.append(("before_raise", RAISED[0], RAISED[1], before_at_raised))

    probes2 = []

    def add2(name, x, y, colour, over_pointer=False):
        if not (0 <= x < fbw and 0 <= y < fbh):
            die("phase-2 probe %s at (%d,%d) is off the screen" % (name, x, y))
        if not over_pointer and under_pointer(x, y, (cx, cy)):
            die("phase-2 probe %s at (%d,%d) is inside the pointer's 12x16 box "
                "at (%d,%d) -- see under_pointer()" % (name, x, y, cx, cy))
        probes2.append((name, x, y, colour))

    # 1. THE RAISE, as a pixel: the window that was underneath is now on top.
    add2("after_raise", RAISED[0], RAISED[1], after_at_raised)
    # 2. THE MOVE, as a pixel: where the window WAS is now the desktop.
    vac = (P["A_X"] + 5, P["A_Y"] + 5)
    if pixel_at(vac[0], vac[1]) != W["wmColorDesktop"]:
        die("the vacated point (%d,%d) is not desktop after the drag; the move "
            "was too small to leave any of the old rectangle uncovered and the "
            "repaint assertion would be vacuous" % vac)
    add2("vacated", vac[0], vac[1], W["wmColorDesktop"])
    # 3. ...and where it now IS holds its own pixels.
    add2("moved_fill", ax2 + inset // 2, ay2 + inset // 2, P["A_FILL"])
    add2("moved_ink", ax2 + w - inset - 10, ay2 + h - inset - 10, P["A_INK"])
    # 4. THE BORDERS SWAPPED. The dragged window is bright now; the other is dim.
    add2("moved_border_focus", ax2 - 1, ay2 + inset, W["wmColorFocus"])
    add2("other_border_unfocus", bx2 + w, by2 + h + b - 1, W["wmColorUnfocus"])
    # 5. The other window is still there where nothing covers it.
    other = None
    for px in range(bx2, bx2 + w):
        if not covers(0, px, by2 + h - 5):
            other = (px + 5, by2 + h - 5)
            break
    if other is None:
        die("the dragged window completely covers the other one; 'the other "
            "window survived' cannot be asserted")
    add2("other_survives", other[0], other[1], pixel_at(other[0], other[1]))
    # 6. THE POINTER, over whatever it ended up on. The clear pixel is the
    #    strongest of the three: there is no save-under, so what shows through
    #    the arrow was RECOMPUTED, and if it comes out right the erase-repaint
    #    used the same picture the compositor would have composed.
    add2("moved_cursor_edge", cx + cur_edge[0], cy + cur_edge[1], edge_c, True)
    add2("moved_cursor_fill", cx + cur_fill[0], cy + cur_fill[1], fill_c, True)
    add2("moved_cursor_clear", cx + cur_clear[0], cy + cur_clear[1],
         pixel_at(cx + cur_clear[0], cy + cur_clear[1]), True)

    # THE PHASE-2 CONTROL: the colour that WAS at the raise probe, asserted
    # after the raise. It must fail, and it is not an arbitrary wrong colour --
    # it is the previous frame's correct one.
    control2 = ("control_stacking_before_raise", RAISED[0], RAISED[1],
                before_at_raised)

    print("win_w=%d" % w)
    print("win_h=%d" % h)
    print("win_pages=%d" % P["WIN_PAGES"])
    print("holdspin=%d" % P["HOLDSPIN"])
    print("border=%d" % b)
    print("overlap=%d %d %d %d" % (ox0, oy0, ox1 - ox0, oy1 - oy0))
    print("overlap_area=%d" % ((ox1 - ox0) * (oy1 - oy0)))
    print("sum_a=%d" % sums[0])
    print("sum_b=%d" % sums[1])
    print("exit_a=%016X" % exit_a)
    print("exit_b=%016X" % exit_b)
    print("frames=4")
    print("px1=%08X" % px1)
    print("px2=%08X" % px2)
    print("px3=%08X" % px3)
    print("px4=%08X" % px4)
    print("dmg_w=%d" % dmg_w)
    print("dmg_h=%d" % dmg_h)
    print("dmg_x=%04X" % dmg_x)
    print("dmg_y=%04X" % dmg_y)
    print("cursor_x=%04X" % p1cx)
    print("cursor_y=%04X" % p1cy)
    print("syscall=%d" % W["wmSysSurfaceNo"])
    print("probe_count=%d" % len(probes))
    for name, x, y, colour in probes:
        print("probe=%s %d %d %08X" % (name, x, y, colour & 0xFFFFFFFF))
    print("control=%s %d %d %08X" % (control[0], control[1], control[2],
                                     control[3] & 0xFFFFFFFF))
    print("drag_raise=%d %d" % (raises[0][1], raises[0][0]))
    print("drag_moves=%d" % moves)
    print("drag_window=%d" % 0)
    print("moved_x=%04X" % ax2)
    print("moved_y=%04X" % ay2)
    print("moved_cursor_x=%04X" % cx)
    print("moved_cursor_y=%04X" % cy)
    print("probe2_count=%d" % len(probes2))
    for name, x, y, colour in probes2:
        print("probe2=%s %d %d %08X" % (name, x, y, colour & 0xFFFFFFFF))
    print("control2=%s %d %d %08X" % (control2[0], control2[1], control2[2],
                                      control2[3] & 0xFFFFFFFF))
    return 0


if __name__ == "__main__":
    sys.exit(main())
