#!/usr/bin/env bash
# verify-freestanding.sh — copied from the DCDart repo
# (core/scripts/verify-freestanding.sh) and adapted, same spine-check
# discipline. Re-synced 2026-08-20 to pick up ADR-0038's extern manifests;
# the ONLY oscortex_core deltas are the env-var name (OSCORTEX_ALLOWLIST),
# the usage line, and the Dart-VM-symbol diagnostic pointing at the DCDart
# repo as the place to file it.
#
# Every kernel object file must link with no runtime. This script is the
# mechanical guarantee of that. A green test suite with a leaked runtime
# symbol is a FAILED change. Run it on every boot/kernel change.
#
# Usage: core/scripts/verify-freestanding.sh build/kernel.o [more.o ...]
#
# ---------------------------------------------------------------------------
# EXTERN MANIFESTS (ADR-0038, docs/escalations/0003-extern-c-calls-vs-
# freestanding.md).
#
# RATIFIED: the project owner decided option 2 on 2026-08-20. That decision
# reached this file relayed through another agent session working in this
# tree, not witnessed firsthand — recorded that way because a change to the
# meaning of CLAUDE.md rule 1 should say on its face where it came from.
#
# Escalation 0003 asked whether an object that deliberately calls an external
# C symbol can still satisfy rule 1, given that calling one MEANS carrying an
# undefined symbol. Its recommendation — option 2, implemented here — is that
# the check distinguishes:
#
#   * a symbol the COMPILER put there without anyone asking (dc_alloc,
#     dc_throw, dc_orc_*, Dart_*) — still a hard failure, always; from
#   * a symbol the AUTHOR declared by name in the source with
#     `@extern external`, which dcc records in <objfile>.externs.
#
# So this script now permits exactly the names in <objfile>.externs, in
# addition to the allowlist, and REPORTS them on every pass so they are
# visible in the log rather than silent (escalation 0003's own first
# condition). The allowlist is untouched and still owned by E4.
#
# What has NOT been weakened: an undefined symbol with no manifest entry and
# no allowlist entry is still a hard failure, and an object with no manifest
# behaves exactly as it did before this existed. Delete an object's manifest
# and its extern calls fail the check again — the conformance harness
# tests exactly that.
#
# Residual risk, stated rather than hidden: the manifest is generated by dcc,
# so it always agrees with the source it was built from, and a hand-written
# manifest could launder a symbol. That is the same trust model the allowlist
# already has. Embedding the declaration set inside the object instead was
# considered and deferred, not forgotten -- see ADR-0038's rejected
# alternatives, and escalation 0003's "what ratification did not settle".
# ---------------------------------------------------------------------------

set -euo pipefail

ALLOWLIST="${OSCORTEX_ALLOWLIST:-tools/bare-symbol-allowlist.txt}"
NM="${NM:-llvm-nm}"

if [[ $# -eq 0 ]]; then
  echo "usage: $0 <objfile> [objfile ...]" >&2
  exit 2
fi

if [[ ! -f "$ALLOWLIST" ]]; then
  echo "FATAL: allowlist not found at $ALLOWLIST" >&2
  echo "The allowlist is owned by E4 (kernel). Do not create one to make this pass." >&2
  exit 2
fi

# Strip comments and blanks from the allowlist.
mapfile -t ALLOWED < <(grep -vE '^\s*(#|$)' "$ALLOWLIST" | sed 's/\s*$//')

# ---------------------------------------------------------------------------
# RESERVED RUNTIME FAMILIES — never honorable, by allowlist OR by manifest.
#
# Ported verbatim from DCDart's copy (that repo's commit 90a9c79) so the two
# scripts stay identical -- this repo inherited the same hole when it adopted
# ADR-0038's manifest support. The hole: a manifest listing `dc_alloc` or
# `Dart_EnterScope` made this script report `FREESTANDING: pass`, contradicting
# both its own header ("still a hard failure, always") and escalation 0003's
# ratified wording.
#
# Why these specifically cannot be declared away: every other undefined symbol
# is a claim about SOMEONE ELSE'S object file, which an author is entitled to
# make. These families are claims about OUR OWN runtime -- they appear because
# the compiler emitted them. Declaring one is not expressing a dependency, it
# is silencing the one check that would catch the language smuggling a runtime
# into @bare.
#
# Deliberately NOT configurable. A safety property with an escape hatch is a
# safety property that will be escaped.
RESERVED=(
  'dc_alloc' 'dc_free' 'dc_realloc'
  'dc_throw' 'dc_unwind' '__gxx_personality*'
  'dc_orc_*'
  'dart_*' 'Dart_*'
)

is_reserved() {
  local sym="$1" pat
  for pat in "${RESERVED[@]}"; do
    # shellcheck disable=SC2053
    if [[ "$sym" == $pat ]]; then return 0; fi
  done
  return 1
}

fail=0

for obj in "$@"; do
  [[ -f "$obj" ]] || { echo "FATAL: no such object: $obj" >&2; exit 2; }

  # Declared externs for THIS object, if any. Exact names only -- no globs.
  # A glob here would let one declaration cover symbols the source never
  # named, which is exactly the drift escalation 0003 warns about.
  DECLARED=()
  MANIFEST="$obj.externs"
  if [[ -f "$MANIFEST" ]]; then
    mapfile -t DECLARED < <(grep -vE '^\s*(#|$)' "$MANIFEST" | sed 's/\s*$//')
  fi

  # Undefined symbols only.
  mapfile -t undef < <("$NM" -u --format=posix "$obj" 2>/dev/null | awk '{print $1}' | sed 's/^_//')

  leaked=()
  honored=()
  for sym in "${undef[@]}"; do
    [[ -z "$sym" ]] && continue
    ok=0
    # Checked FIRST, so neither the allowlist nor the manifest can honor it.
    if is_reserved "$sym"; then
      leaked+=("$sym")
      continue
    fi
    for a in "${ALLOWED[@]}"; do
      # Allowlist entries may be exact names or shell globs (e.g. __aeabi_*).
      # shellcheck disable=SC2053
      if [[ "$sym" == $a ]]; then ok=1; break; fi
    done
    if (( ! ok )); then
      for d in "${DECLARED[@]}"; do
        if [[ "$sym" == "$d" ]]; then ok=1; honored+=("$sym"); break; fi
      done
    fi
    (( ok )) || leaked+=("$sym")
  done

  # A manifest entry that no undefined symbol matches means the manifest and
  # the object disagree -- a stale manifest, a renamed symbol, or a call the
  # optimizer removed. Report it, but do not fail: it PERMITS nothing, so it
  # cannot hide a leak. Silence would be worse than noise here.
  for d in "${DECLARED[@]}"; do
    [[ -z "$d" ]] && continue
    found=0
    for sym in "${undef[@]}"; do
      if [[ "$sym" == "$d" ]]; then found=1; break; fi
    done
    (( found )) || echo "  note: declared extern \"$d\" is not undefined in $obj (stale manifest entry?)"
  done

  if (( ${#leaked[@]} )); then
    fail=1
    echo "FREESTANDING: FAIL  $obj"
    for sym in "${leaked[@]}"; do
      case "$sym" in
        dc_alloc|dc_free|dc_realloc)
          echo "  $sym  -> implicit allocation. A closure escaped, a String was built, or a collection grew." ;;
        dc_throw|dc_unwind|__gxx_personality*)
          echo "  $sym  -> a throw reached @bare, usually via a @hosted library call." ;;
        dc_orc_*)
          echo "  $sym  -> cycle collector reference. A @hosted type leaked into @bare." ;;
        dart_*|Dart_*)
          echo "  $sym  -> old Dart VM runtime symbol. This is a DCDart backend bug, not an oscortex_core one -- file it against the DCDart repo." ;;
        *)
          echo "  $sym  -> undefined, not allowlisted, and not declared @extern in the source." ;;
      esac
      if is_reserved "$sym"; then
        echo "  NOTE: \"$sym\" is a RESERVED runtime name. Declaring it @extern will"
        echo "        NOT make this pass -- reserved names are matched before the"
        echo "        allowlist and before the manifest, on purpose."
      fi
    done
    echo "  Do NOT add to the allowlist to make this pass. The allowlist is owned by E4."
    echo "  If this symbol is a deliberate C dependency, declare it in the DCDart"
    echo "  source as \`@extern external ...\` so dcc records it (ADR-0038)."
  else
    if (( ${#honored[@]} )); then
      echo "FREESTANDING: pass  $obj  (${#honored[@]} declared extern(s): ${honored[*]})"
    else
      echo "FREESTANDING: pass  $obj"
    fi
  fi
done

exit $fail
